version: '3.8'
services:
  webserver:
    container_name: imgbed
    build: .
    ports:
      - "80:80"
    volumes:
      - ./:/var/www/html
    environment:
      XDEBUG_CONFIG: remote_host=10.42.84.204